# Generated by Django 4.1.3 on 2024-07-25 11:55

import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contact_num', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('marritial_status', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=30)),
                ('isAdmin', models.BooleanField(default=False)),
                ('family_members', models.TextField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=100)),
                ('secretary', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('contact_num', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('marritial_status', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=30)),
                ('isAdmin', models.BooleanField(default=False)),
                ('family_members', models.TextField(blank=True, max_length=80, null=True)),
                ('flat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.flat')),
                ('wing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.wing')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('pcd', models.DateTimeField(default=datetime.datetime(2024, 7, 25, 11, 55, 33, 618181, tzinfo=datetime.timezone.utc))),
                ('prd', models.DateTimeField(default=datetime.datetime(2024, 7, 25, 11, 55, 33, 618181, tzinfo=datetime.timezone.utc))),
                ('flat', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='flat', to='main.flat')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('wing', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wing', to='main.wing')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='wing_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat', to='main.wing'),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.flat'),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='wing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.wing'),
        ),
    ]
