# Generated by Django 4.1.3 on 2024-07-25 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='pcd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 12, 2, 23, 26085, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 12, 2, 23, 26085, tzinfo=datetime.timezone.utc)),
        ),
    ]
