# Generated by Django 4.1.3 on 2024-07-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='family_members',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
