# Generated by Django 4.1.3 on 2024-07-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_member_family_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='flat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='flat', to='main.flat'),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='wing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wing', to='main.wing'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='main.member'),
        ),
    ]
