# Generated by Django 4.1.3 on 2024-07-25 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_issue_pcd_alter_issue_prd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='pcd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 13, 31, 42, 896268, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 13, 31, 42, 896268, tzinfo=datetime.timezone.utc)),
        ),
    ]
