# Generated by Django 4.1.3 on 2024-07-07 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_issue_flat_issue_status_issue_wing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pcd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 14, 38, 18, 17450, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='issue',
            name='prd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 14, 38, 18, 17450, tzinfo=datetime.timezone.utc)),
        ),
    ]
