# Generated by Django 4.1.3 on 2024-07-07 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_issue_pcd_issue_prd'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='pcd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 15, 35, 21, 387270, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 7, 15, 35, 21, 387270, tzinfo=datetime.timezone.utc)),
        ),
    ]
