# Generated by Django 4.1.3 on 2024-07-13 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_issue_pcd_alter_issue_prd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='pcd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 5, 29, 5, 98059, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prd',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 5, 29, 5, 98059, tzinfo=datetime.timezone.utc)),
        ),
    ]
